import os

TELEGRAM_TOKEN = os.getenv('TELEGRAM_TOKEN')
CHANNEL_ID = os.getenv('CHANNEL_ID')
BOT_OWNER_ID = os.getenv('BOT_OWNER_ID')
PASTEBIN_API_KEY = os.getenv('PASTEBIN_API_KEY')
URL_SHORTENER_API_KEY = os.getenv('URL_SHORTENER_API_KEY')
